name: NetflixMovieCatalog Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |                 
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          IMAGE_NAME=netflix-movie-catalog:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          
          DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKER_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}

                  if [ -z $DOCKER_USERNAME ] || [ -z $DOCKER_PASSWORD ]; then
                    echo DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD secrets should be configured
                    exit 1
                  fi
